# Site settings
title: Mon Amie Déco - Solucionando pequenos espaços
name: Mon Amie Déco
description: >
  Mon Amie Déco Arquitetura e Decoração: Solucionando pequenos espaços
url: "http://monamiedeco.com"
baseurl: ""
postimgpath: "/assets/posts"
fburl: https://www.facebook.com/tuttideli

# Post settings
permalink: /:title

# Author settings
author: Sabrina Guimarães
authorimg: assets/sabry.png
authordesc: |
  arquiteta especializada em solucionar e otimizar pequenos espaços.

# Build settings
markdown: kramdown
