# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mon Amie Déco
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Mon Amie Déco Arquitetura e Decoração: solucionando pequenos espaços
baseurl: "/mad" # the subpath of your site, e.g. /blog
url: "http://monamiedeco.com" # the base hostname & protocol for your site
author: Sabrina Guimarães
authorimg: assets/sabry.png
authordesc: |
  Sabrina Guimarães, arquiteta especializada em solucionar e otimizar pequenos
  espaços.

# Build settings
markdown: kramdown
