# Site settings
title: Mon Amie Déco
description: > # this means to ignore newlines until "baseurl:"
  Mon Amie Déco Arquitetura e Decoração: solucionando pequenos espaços

# URLs
url: http://monamiedeco.com
baseurl: ""
fburl: https://www.facebook.com/tuttideli

# Post settings
permalink: /:title

# Author settings
author: Sabrina Guimarães
authorimg: assets/sabry.png
authordesc: |
  Sabrina Guimarães, arquiteta especializada em solucionar e otimizar pequenos
  espaços.

# Build settings
markdown: kramdown
